name: CI - Docker Build & Push (AUTODEPLOY-MICROSERVICE)

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'backend/k8s/**'

permissions:
  contents: write

jobs:
  # ======================
  # Deployer App
  # ======================
  AUTODEPLOY-MICROSERVICE-CI:
    runs-on: self-hosted
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      GIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install test dependencies
        run: pip install -r test-requirements.txt

      - name: Linting (Flake8)
        run: flake8 backend || true
        continue-on-error: true

      - name: Unit Tests (pytest)
        run: pytest backend/tests || true
        continue-on-error: true

      - name: SAST (CodeQL Analysis)
        uses: github/codeql-action/analyze@v2
        continue-on-error: true

      - name: SCA (Safety)
        run: safety check -r backend/requirements.txt || true
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Image Build Deployer App (Git SHA)
        run: |
          cd backend
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/deployer-app:${{ env.GIT_SHA }} -f deployer-dockerfile .

      - name: Image Scan (Trivy - Deployer App)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_HUB_USERNAME }}/deployer-app:${{ env.GIT_SHA }}
          format: table
          exit-code: 0
          scanners: secret
        continue-on-error: true

      - name: Image Push Deployer App (Git SHA)
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/deployer-app:${{ env.GIT_SHA }}

      - name: Update Deployment manifest
        run: |
          sed -i "s|image:.*deployer-app.*|image: ${{ env.DOCKER_HUB_USERNAME }}/deployer-app:${{ env.GIT_SHA }}|" backend/k8s/deployment/deployer-deployment.yaml

      - name: Commit & Push Deployment Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add backend/k8s/deployment/deployer-deployment.yaml
          git diff --staged --quiet || git commit -m "Update deployer-app image to ${{ env.GIT_SHA }} [skip ci]"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
